name: my_messenger

networks:
  mynet:
    driver: bridge
volumes:
  db_data:
    driver: local
services:
  authServer:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8080:8080
    networks:
      - mynet
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
  server:
    build: ../TeleBan
    restart: always
    ports:
      - 5095:80 
    depends_on:
      - authServer
      - db
    networks:
      - mynet
    environment:
      DB_SERVER: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: mysql
  client:
    build: 
      context: ../client
    ports:
      - 3000:3000
    depends_on:
      - server
      - authServer
    environment:
      REACT_APP_KEYCLOAK_REALM: master
      REACT_APP_KEYCLOAK_CLIENT_ID: myclient
      REACT_APP_GRAPHQL_URL: http://localhost:5095/graphql
      REACT_APP_WS_GRAPHQL_URL: ws://localhost:5095/graphql
      REACT_APP_KEYCLOACK_URL: http://localhost:8080
      
  db:
    image: mysql
    ports:
        - "3306:3306"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynet
